### 회원가입
POST http://localhost:3000/users
Content-Type: application/json

{
  "email": "testuser@gmail.com",
  "name": "name",
  "password": "testpassword1234",
  "roles": ["ADMIN"]
}


### 로그인
POST http://localhost:3000/auth/login
Content-Type: application/json

{
"email": "testuser@gmail.com",
"password": "testpassword1234"
}

> {% client.global.set("accessToken", response.body.accessToken) %}
