services:
  mongo-auth:
    image: mongo
    container_name: mongo-auth
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: authpass
    volumes:
      - mongo-auth-data:/data/db

  mongo-event:
    image: mongo
    container_name: mongo-event
    ports:
      - '27018:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: eventpass
    volumes:
      - mongo-event-data:/data/db

volumes:
  mongo-auth-data:
  mongo-event-data:
