services:
  gateway-server:
    image: gateway-server
    build:
      context: ./gateway-server
      dockerfile: Dockerfile
    environment:
      - AUTH_SERVICE_URL=http://auth-server:3000
      - EVENT_SERVICE_URL=http://event-server:3000
    ports:
      - '3000:3000'
    networks:
      - app-networks

  auth-server:
    image: auth-server
    build:
      context: ./auth-server
      dockerfile: Dockerfile
    environment:
      - PORT=3000
    networks:
      - app-networks

  event-server:
    image: event-server
    build:
      context: ./event-server
      dockerfile: Dockerfile
    environment:
      - PORT=3000
    networks:
      - app-networks

networks:
  app-networks:
