services:
  # Gateway 서버
  gateway-server:
    image: gateway-server
    build:
      context: gateway-server
      dockerfile: Dockerfile
    environment:
      - PORT=3000
      - AUTH_SERVICE_URL=http://auth-server:3000
      - EVENT_SERVICE_URL=http://event-server:3000
      - JWT_SECRET_KEY=jwt-secret-key
    ports:
      - '3000:3000'
    networks:
      - app-networks

  # Auth 서버
  auth-server:
    image: auth-server
    build:
      context: auth-server
      dockerfile: Dockerfile
    environment:
      PORT: 3000
      MONGODB_URI: mongodb://mongo-auth:27017
      JWT_SECRET_KEY: jwt-secret-key
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: authpass
    networks:
      - app-networks

  mongo-auth:
    image: mongo
    container_name: mongo-auth
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: authpass
    networks:
      - app-networks

  # Event 서버
  event-server:
    image: event-server
    build:
      context: event-server
      dockerfile: Dockerfile
    environment:
      PORT: 3000
      MONGODB_URI: mongodb://mongo-event:27017
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: eventpass
    networks:
      - app-networks

  mongo-event:
    image: mongo
    container_name: mongo-event
    ports:
      - '27018:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: eventpass
    networks:
      - app-networks

networks:
  app-networks:
